# Generated by Django 4.1 on 2022-08-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='products',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.PositiveIntegerField(verbose_name='оценка'),
        ),
    ]
